{% set name = "geoarrow-c" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoarrow-c-{{ version }}.tar.gz
  sha256: 73be8739c10c7c2261c54ddca77c977c71ee4285af4b3d812c12192bd1f46a24

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=61.0.0
    - setuptools-scm
    - cython
    - pip
    - libcxx
  run:
    - python
    - libcxx

test:
  imports:
    - geoarrow.c
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geoarrow/geoarrow-c
  summary: Low-level Python bindings to the GeoArrow C implementation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - paleolimbot
